### ISSUE TITLE
Question about the data generation

### ISSUE THREAD

**Issue by WisonZ** [mk-minchul/dcface#2]

**Comment by WisonZ** [comment]
adaface_ir101_webface4m.ckpt missing

**Comment by WisonZ** [comment]
recognition_eval != recognition && recognition_eval['ckpt_path]=None => download_ir_pretrained_statedict() in recognition_helper.py (line 33)

**Comment by CKK-coder** [comment]
Hello, have you resolved this issue yet？

**Comment by Tokymin** [comment]
Hello, have you found this file？

**Comment by WisonZ** [comment]
just download from adaface

**Comment by Tokymin** [comment]
> just download from insightface

Thanks for your reply! could you send me the link for the insightface? I don't konw what is this, thank you very much!!

**Comment by Tokymin** [comment]
> just download from insightface

hello, could you give me more details please? I would be very grateful for that!

**Comment by WisonZ** [comment]
download from AdaFace: https://github.com/mk-minchul/AdaFace
Download: https://drive.google.com/file/d/18jQkqB0avFqWa0Pas52g54xNshUOQJpQ/view
