### ISSUE TITLE
Errors when training with higher resolution

### ISSUE THREAD

**Issue by tyrink** [mk-minchul/dcface#22]
Hi, thanks for your great work! I have tried to train the data generation model at 256*256 resolution, but after modifying the 'datamodule.image_size=256', I came across the errors below. However, even confronting this, the model can still continue training with bad effects. And I just cannot figure out what is going on.
![image](https://github.com/mk-minchul/dcface/assets/75239935/131e0951-6543-4345-b77a-c9d73fe6a876)

**Comment by Glisten-5481** [comment]
Sorry to bother you, have you resolved this problem? @tyrink
